# Generated by Django 3.0.6 on 2020-06-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pi_hide',
            field=models.BooleanField(default=False),
        ),
    ]
