# Generated by Django 3.0.6 on 2020-06-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_pi_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pi_hide',
            field=models.BooleanField(null=True),
        ),
    ]
