# Generated by Django 3.0.6 on 2020-06-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_userprofile_pi_hide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pi_hide',
        ),
    ]
