# Generated by Django 2.1.7 on 2020-06-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_user_pi_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pi_hide',
            field=models.NullBooleanField(),
        ),
    ]
