FROM python:3.7-alpine3.9

ENV OJ_ENV production

RUN mkdir /app;mkdir /dist
ADD ./deploy/requirements.txt /tmp
WORKDIR /tmp

HEALTHCHECK --interval=5s --retries=3 CMD python2 /app/deploy/health_check.py

RUN apk add --update --no-cache build-base nginx openssl curl unzip supervisor jpeg-dev zlib-dev postgresql-dev freetype-dev && \
    pip install --no-cache-dir -r /tmp/requirements.txt && \
    apk del build-base --purge

ENTRYPOINT /bin/sleep 3600
