# Generated by Django 2.1.7 on 2020-06-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_auto_20190326_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='virtual_contest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='virtual_contest_duration',
            field=models.IntegerField(default=3600),
        ),
    ]
